blank_issues_enabled: false
contact_links:
  - name: Reportar una vulnerabilidad
    url: https://github.com/Mati-dubs-dev/pomodoro-flutter-app/security/advisories/new
    about: Comunica problemas de seguridad mediante un reporte privado.
